from .nodes import NODE_CLASS_MAPPINGS as _PROMPT_NODES, NODE_DISPLAY_NAME_MAPPINGS as _PROMPT_NAMES
from .vfile_random import NODE_CLASS_MAPPINGS as _FILE_NODES, NODE_DISPLAY_NAME_MAPPINGS as _FILE_NAMES
from .vrandom_selector import NODE_CLASS_MAPPINGS as _SELECT_NODES, NODE_DISPLAY_NAME_MAPPINGS as _SELECT_NAMES
from .vwait_vram import NODE_CLASS_MAPPINGS as _WAIT_NODES, NODE_DISPLAY_NAME_MAPPINGS as _WAIT_NAMES

NODE_CLASS_MAPPINGS = {**_PROMPT_NODES, **_FILE_NODES, **_SELECT_NODES, **_WAIT_NODES}
NODE_DISPLAY_NAME_MAPPINGS = {**_PROMPT_NAMES, **_FILE_NAMES, **_SELECT_NAMES, **_WAIT_NAMES}

WEB_DIRECTORY = "./web"
__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
